#!/usr/bin/env python3
"""Cooperative atomic claim / status helper for the sunaba multi-agent
shared task list.

This script is generated by `sunaba-cli` when `--stack multi-agent`
is selected. It is committed into the project and edited by the
project owner.

Atomicity:
- When `fcntl.flock` is available (POSIX), every transition takes an
  exclusive lock on `.agents/multi-agent/tasks.lock` for the whole
  read-validate-mutate-rename cycle.
- When `flock` is unavailable (Windows, certain Docker overlays),
  fall back to optimistic concurrency: hash-check `tasks.yaml` after
  read; on mismatch, retry with backoff up to 5 times.

Schema validation:
- If `jsonschema` is importable, every transition validates the
  resulting `tasks.yaml` against `schema.json` before writing. If
  not, fall back to a minimal hand-rolled check.

Cooperative, not enforced:
- This script makes the right thing easy. It does not prevent a
  misbehaving agent from editing `tasks.yaml` by hand or skipping
  the script entirely. The discipline is documented in
  `AGENTS.md` and `docs/multi-agent/orchestration.md`.

Exit codes:
  0 = success
  2 = overlap / ownership violation
  3 = stale claim or task-not-found
  4 = schema error
  5 = lock timeout
  6 = bad arguments
"""

from __future__ import annotations

import argparse
import datetime
import fnmatch
import hashlib
import os
import sys
import tempfile
import time
from contextlib import contextmanager
from pathlib import Path

try:
    import jsonschema  # type: ignore[import-untyped]
    _HAS_JSONSCHEMA = True
except ImportError:
    _HAS_JSONSCHEMA = False

try:
    import fcntl  # type: ignore[import-untyped]
    _HAS_FLOCK = True
except ImportError:
    _HAS_FLOCK = False


def _require_yaml():
    """Lazy yaml import. Lets `--help` and pure-function tests run
    without PyYAML installed; only the actual file-IO subcommands
    need it."""
    try:
        import yaml  # type: ignore[import-untyped]
        return yaml
    except ImportError:
        print(
            "agent-task.py requires PyYAML. Install with `pip install pyyaml`.",
            file=sys.stderr,
        )
        sys.exit(6)


# Anchor every path under .agents/multi-agent/ so the script behaves
# identically whether you run it from the repo root or a worktree.
STATE_DIR = Path(".agents/multi-agent")
TASKS_PATH = STATE_DIR / "tasks.yaml"
SCHEMA_PATH = STATE_DIR / "schema.json"
LOCK_PATH = STATE_DIR / "tasks.lock"

EXIT_OK = 0
EXIT_OVERLAP = 2
EXIT_NOT_FOUND = 3
EXIT_SCHEMA = 4
EXIT_LOCK = 5
EXIT_USAGE = 6

VALID_STATUSES = (
    "pending", "claimed", "in_progress",
    "blocked", "review", "completed", "failed",
)


# ---------- atomicity ----------


@contextmanager
def _acquire_lock(timeout_seconds: float = 10.0):
    """Yield with an exclusive lock when flock is available; otherwise
    yield a sentinel for the optimistic path."""
    if not _HAS_FLOCK:
        yield None
        return

    STATE_DIR.mkdir(parents=True, exist_ok=True)
    LOCK_PATH.touch(exist_ok=True)
    start = time.monotonic()
    fd = os.open(str(LOCK_PATH), os.O_RDWR)
    try:
        while True:
            try:
                fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
                break
            except (BlockingIOError, OSError):
                if time.monotonic() - start > timeout_seconds:
                    raise SystemExit(EXIT_LOCK)
                time.sleep(0.1)
        yield fd
    finally:
        try:
            fcntl.flock(fd, fcntl.LOCK_UN)
        finally:
            os.close(fd)


def _read_tasks() -> tuple[dict, str]:
    """Return (parsed_yaml, sha256_hex_of_raw_text)."""
    if not TASKS_PATH.exists():
        print(f"error: {TASKS_PATH} not found", file=sys.stderr)
        raise SystemExit(EXIT_NOT_FOUND)
    yaml = _require_yaml()
    raw = TASKS_PATH.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    data = yaml.safe_load(raw.decode("utf-8")) or {}
    return data, digest


def _write_tasks_atomic(data: dict) -> None:
    """Write tasks.yaml via tmp + rename so observers never see a
    half-written file."""
    yaml = _require_yaml()
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    payload = yaml.safe_dump(
        data, sort_keys=False, allow_unicode=True, default_flow_style=False
    )
    fd, tmp_path = tempfile.mkstemp(
        prefix=".tasks.", suffix=".yaml.tmp", dir=str(STATE_DIR)
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(payload)
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp_path, TASKS_PATH)
    except Exception:
        try:
            os.unlink(tmp_path)
        except FileNotFoundError:
            pass
        raise


# ---------- schema ----------


def _validate(data: dict) -> None:
    """Validate against schema.json if jsonschema is available; otherwise
    apply a minimal hand-rolled check."""
    if _HAS_JSONSCHEMA and SCHEMA_PATH.exists():
        import json
        schema = json.loads(SCHEMA_PATH.read_text())
        try:
            jsonschema.validate(data, schema)
        except jsonschema.ValidationError as e:
            print(f"schema error: {e.message}", file=sys.stderr)
            raise SystemExit(EXIT_SCHEMA)
        return
    # Fallback minimal checks.
    if data.get("version") != 1:
        print("schema error: version != 1", file=sys.stderr)
        raise SystemExit(EXIT_SCHEMA)
    if "cohort" not in data or "tasks" not in data:
        print("schema error: missing cohort or tasks", file=sys.stderr)
        raise SystemExit(EXIT_SCHEMA)
    for t in data["tasks"]:
        if t.get("status") not in VALID_STATUSES:
            print(
                f"schema error: invalid status {t.get('status')!r} on {t.get('id')}",
                file=sys.stderr,
            )
            raise SystemExit(EXIT_SCHEMA)


# ---------- queries (used by tests too) ----------


def has_overlap(owns_a: list[str], owns_b: list[str]) -> bool:
    """Return True if any glob in `owns_a` could match a path that any
    glob in `owns_b` could match. Uses fnmatch on a small set of
    representative substitutions; not a full glob solver."""
    def _candidates(globs: list[str]) -> set[str]:
        out: set[str] = set()
        for g in globs:
            out.add(g)
            out.add(g.replace("**", "anything"))
            out.add(g.replace("**/", ""))
            out.add(g.replace("/**", ""))
            out.add(g.replace("**", "x").replace("*", "x"))
        return out

    cand_b = _candidates(owns_b)
    for g in owns_a:
        for c in cand_b:
            if fnmatch.fnmatchcase(c, g):
                return True
    for g in owns_b:
        for c in _candidates(owns_a):
            if fnmatch.fnmatchcase(c, g):
                return True
    return False


def path_matches_owns(path: str, owns: list[str]) -> bool:
    """Return True if `path` matches at least one glob in `owns`."""
    for g in owns:
        if fnmatch.fnmatchcase(path, g):
            return True
        # Treat `**` as recursive prefix on a literal directory.
        if "**" in g:
            normalized = g.replace("/**", "/").replace("**/", "")
            if path.startswith(normalized) or fnmatch.fnmatchcase(
                path, g.replace("**", "*")
            ):
                return True
    return False


def recommend_agents(
    *,
    files: int,
    components: int,
    has_schema_change: bool,
    has_shared_file: bool = False,
    max_cap: int = 4,
) -> int:
    """Pure-function shard count recommendation. Mirrors the flowchart.

    Returns 1 for serial, otherwise 2..max_cap.
    """
    if has_schema_change:
        return 1
    if files <= 1:
        return 1
    if components < 2:
        return 1
    if files <= 4 and components <= 1:
        return 1
    # Step 7: shared file → serial prerequisite, planning treats this
    # as 1 agent for now.
    if has_shared_file:
        return 1
    if components < 3 and files <= 4:
        return 1
    if files <= 5:
        return min(2, max_cap)
    if components <= 5:
        return min(2, max_cap)
    if components <= 10:
        return min(3, max_cap)
    return min(4, max_cap)


# ---------- transitions ----------


def _now_utc() -> str:
    return datetime.datetime.now(datetime.timezone.utc).isoformat(
        timespec="seconds"
    )


def _find_task(data: dict, task_id: str) -> dict | None:
    for t in data.get("tasks", []):
        if t.get("id") == task_id:
            return t
    return None


def _other_active(data: dict, task_id: str) -> list[dict]:
    """Tasks that are claimed or in_progress, excluding `task_id`."""
    return [
        t for t in data.get("tasks", [])
        if t.get("id") != task_id
        and t.get("status") in ("claimed", "in_progress")
    ]


def _transition(task_id: str, mutate) -> int:
    with _acquire_lock():
        # Optimistic-concurrency retry on hash mismatch when flock is
        # unavailable.
        attempts = 5 if not _HAS_FLOCK else 1
        backoff = 0.1
        last_err: str | None = None
        for attempt in range(attempts):
            data, digest_before = _read_tasks()
            task = _find_task(data, task_id)
            if task is None:
                print(f"error: task {task_id!r} not found", file=sys.stderr)
                return EXIT_NOT_FOUND
            err = mutate(task, data)
            if err is not None:
                # Mutation returned a (exit_code, message) — surface and stop.
                code, message = err
                print(f"error: {message}", file=sys.stderr)
                return code
            _validate(data)
            if not _HAS_FLOCK:
                # Optimistic write: re-read to confirm digest didn't shift.
                if TASKS_PATH.read_bytes() and hashlib.sha256(
                    TASKS_PATH.read_bytes()
                ).hexdigest() != digest_before:
                    last_err = "concurrent write detected; retrying"
                    time.sleep(backoff)
                    backoff *= 2
                    continue
            _write_tasks_atomic(data)
            print(f"{task_id}: {task.get('status')}")
            return EXIT_OK
        print(
            f"error: optimistic-concurrency retries exhausted: {last_err}",
            file=sys.stderr,
        )
        return EXIT_LOCK


# ---------- subcommands ----------


def cmd_list(args: argparse.Namespace) -> int:
    data, _ = _read_tasks()
    for t in data.get("tasks", []):
        print(
            f"{t['id']:6} {t['status']:12} "
            f"claimed_by={t.get('claimed_by') or '-':<24} "
            f"owns={','.join(t.get('owns') or [])}"
        )
    return EXIT_OK


def cmd_status(args: argparse.Namespace) -> int:
    data, _ = _read_tasks()
    cohort = data.get("cohort", {})
    by_status: dict[str, int] = {}
    for t in data.get("tasks", []):
        by_status[t["status"]] = by_status.get(t["status"], 0) + 1
    print(f"cohort: {cohort.get('id')}")
    print(
        f"max_agents: env {cohort.get('max_agents_env')} "
        f"(default {cohort.get('default_max_agents')})"
    )
    for s in VALID_STATUSES:
        if s in by_status:
            print(f"  {s:12} {by_status[s]}")
    return EXIT_OK


def cmd_claim(args: argparse.Namespace) -> int:
    def mutate(task: dict, data: dict):
        if task["status"] != "pending":
            return (
                EXIT_OVERLAP,
                f"task {task['id']} is {task['status']}, not pending",
            )
        # Overlap guard: refuse if any active task has overlapping owns.
        for other in _other_active(data, task["id"]):
            if has_overlap(task.get("owns", []), other.get("owns", [])):
                return (
                    EXIT_OVERLAP,
                    f"owns overlaps with active task {other['id']}",
                )
        task["status"] = "claimed"
        task["claimed_by"] = args.agent
        if args.kind:
            task["agent_kind"] = args.kind
        task["updated_at"] = _now_utc()
        return None
    return _transition(args.task_id, mutate)


def cmd_start(args: argparse.Namespace) -> int:
    def mutate(task: dict, _data):
        if task["status"] != "claimed":
            return (EXIT_OVERLAP, f"task {task['id']} is {task['status']}, not claimed")
        task["status"] = "in_progress"
        task["started_at"] = task.get("started_at") or _now_utc()
        task["updated_at"] = _now_utc()
        return None
    return _transition(args.task_id, mutate)


def cmd_complete(args: argparse.Namespace) -> int:
    def mutate(task: dict, _data):
        if task["status"] not in ("in_progress", "review", "claimed"):
            return (EXIT_OVERLAP, f"task {task['id']} is {task['status']}, cannot complete")
        task["status"] = "completed"
        task["updated_at"] = _now_utc()
        return None
    return _transition(args.task_id, mutate)


def cmd_fail(args: argparse.Namespace) -> int:
    def mutate(task: dict, _data):
        task["status"] = "failed"
        task["updated_at"] = _now_utc()
        task["failure"] = {
            "kind": args.kind or "other",
            "detail": args.reason,
            "next_action": args.next_action,
        }
        return None
    return _transition(args.task_id, mutate)


def cmd_block(args: argparse.Namespace) -> int:
    def mutate(task: dict, _data):
        task["status"] = "blocked"
        task["updated_at"] = _now_utc()
        detail = args.reason
        if args.files:
            detail = f"{detail} :: needs {','.join(args.files)}"
        task["failure"] = {
            "kind": args.kind or "needs_owns_expansion",
            "detail": detail,
            "next_action": args.next_action,
        }
        return None
    return _transition(args.task_id, mutate)


def cmd_check_owns(args: argparse.Namespace) -> int:
    data, _ = _read_tasks()
    task = _find_task(data, args.task_id)
    if task is None:
        print(f"error: task {args.task_id!r} not found", file=sys.stderr)
        return EXIT_NOT_FOUND
    if path_matches_owns(args.path, task.get("owns") or []):
        print(f"OK: {args.path} is owned by {args.task_id}")
        return EXIT_OK
    print(
        f"REFUSE: {args.path} is NOT in {args.task_id} owns: "
        f"{task.get('owns')}",
        file=sys.stderr,
    )
    return EXIT_OVERLAP


def cmd_overlap(args: argparse.Namespace) -> int:
    data, _ = _read_tasks()
    a = _find_task(data, args.task_a)
    b = _find_task(data, args.task_b)
    if a is None or b is None:
        print("error: one or both tasks not found", file=sys.stderr)
        return EXIT_NOT_FOUND
    if has_overlap(a.get("owns") or [], b.get("owns") or []):
        print(f"OVERLAP: {args.task_a} and {args.task_b} share files")
        return EXIT_OVERLAP
    print(f"OK: {args.task_a} and {args.task_b} are non-overlapping")
    return EXIT_OK


# ---------- argparse wiring ----------


def _build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(
        prog="agent-task",
        description="Cooperative claim / status helper for the sunaba multi-agent task list.",
    )
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("list", help="print every task as one line")
    sub.add_parser("status", help="cohort summary")

    pc = sub.add_parser("claim", help="pending → claimed")
    pc.add_argument("task_id")
    pc.add_argument("--agent", required=True)
    pc.add_argument("--kind", choices=["claude", "codex", "gemini", "human"])

    ps = sub.add_parser("start", help="claimed → in_progress")
    ps.add_argument("task_id")

    pco = sub.add_parser("complete", help="in_progress → completed")
    pco.add_argument("task_id")

    pf = sub.add_parser("fail", help="* → failed")
    pf.add_argument("task_id")
    pf.add_argument("--reason", required=True)
    pf.add_argument("--kind", choices=[
        "overlap", "test_failure", "dependency_missing",
        "unclear_scope", "needs_owns_expansion", "other"
    ])
    pf.add_argument("--next-action", dest="next_action")

    pb = sub.add_parser("block", help="* → blocked")
    pb.add_argument("task_id")
    pb.add_argument("--reason", required=True)
    pb.add_argument("--kind", choices=[
        "overlap", "test_failure", "dependency_missing",
        "unclear_scope", "needs_owns_expansion", "other"
    ])
    pb.add_argument("--files", nargs="+", default=None)
    pb.add_argument("--next-action", dest="next_action")

    pchk = sub.add_parser(
        "check-owns",
        help="exit 0 if path is in task's owns:; exit 2 otherwise",
    )
    pchk.add_argument("task_id")
    pchk.add_argument("path")

    po = sub.add_parser(
        "overlap",
        help="exit 0 if two tasks have non-overlapping owns:; exit 2 if overlap",
    )
    po.add_argument("task_a")
    po.add_argument("task_b")
    return p


_DISPATCH = {
    "list":       cmd_list,
    "status":     cmd_status,
    "claim":      cmd_claim,
    "start":      cmd_start,
    "complete":   cmd_complete,
    "fail":       cmd_fail,
    "block":      cmd_block,
    "check-owns": cmd_check_owns,
    "overlap":    cmd_overlap,
}


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    fn = _DISPATCH[args.cmd]
    return fn(args)


if __name__ == "__main__":
    sys.exit(main())
